name: integration
on: [push]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
      env:
        CI: true
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        TEST_LIB: false
        CC_TEST_REPORTER_ID: 1e22bddb55d151988de2f0a971c33178da971f43c951c4d6694b519487cdb1f8
        CI: true
      with:
        coverageCommand: npm run coverage
        debug: true